In [2]:
import numpy as np

array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
# 1 to 3 array
array = np.arange(4)
print(array)

array2 = np.zeros((4, 4), dtype=float)
print(array2)

array3 = np.ones((3, 3,), dtype=str)
print(array3)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [4]:
# 0 to 9 random array

array4 = np.random.randint(0, 10, (3, 3))
print(array4)

# mean is 0, standard deviation is 1 random array

array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[8 6 4]
 [0 0 9]
 [0 0 4]]
[[-0.55505214  0.92206704  0.14473409]
 [-1.07601159 -1.22293713  1.13766374]
 [ 0.15906146 -0.03536301  0.46838502]]


concatenate array

In [5]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [6]:
array1 = np.arange(4).reshape(4, 1)
array2 = np.arange(8).reshape(4, 2)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis=1)
print(array3)

[[0]
 [1]
 [2]
 [3]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 0 1]
 [1 2 3]
 [2 4 5]
 [3 6 7]]


array split

In [7]:
array = np.arange(8).reshape(2, 4)
# vertical split
left, right = np.split(array, [2], axis=1)

print(left)
print(right)

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


numpy ops

In [10]:
array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)

[[3 4]
 [1 5]]


In [13]:
result_array = array * 10
print(result_array)

[[30 40]
 [10 50]]


In [15]:
result_array = array + 10
print(result_array)

[[13 14]
 [11 15]]


Broadcasting 이 되어, 서로 다른 배열도 연산이 된다.

In [19]:
array1 = np.random.randint(1, 10, size=2).reshape(1, 2)
print(array)
print(array1)
print(array + array1)

# broadcasting

[[3 4]
 [1 5]]
[[4 4]]
[[7 8]
 [5 9]]


In [25]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3)

array4 = np.arange(0, 4).reshape(4, 1)
print(array4)

print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


masked array : 마스킹 연산

In [33]:
array1 = np.arange(16).reshape(4, 4)
print(array1)
array2 = array1 < 10
print(array2)

array1[array2] = 100
# if array2 is true, array1 value is 100
print(array1)
# array1 is masked array.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [41]:
array = np.arange(16).reshape(4, 4)
print("max val of arr:", np.max(array))
print("min val of arr:", np.min(array))
print("sum of arr:", np.sum(array))
print("mean of arr:", np.mean(array))
print()

print("sum of arr axis=0:", np.sum(array, axis=0))

max val of arr: 15
min val of arr: 0
sum of arr: 120
mean of arr: 7.5

sum of arr axis=0: [24 28 32 36]


Save and load in numpy

In [46]:
array = np.arange(0, 10)
np.save('saved.npy', array)
# save array to saved.npy

result = np.load('saved.npy').reshape(2, 5)
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# also can save&load multiple array
array1 = np.arange(0, 10)
array2 = np.aragen(10, 20)

np.savez('saved.npz', array1=array1, array2=array2)

Numpy sorting

In [53]:
# sorting to upper case
array = np.array([5, 9, 10, 3, 1])
print("Before sorting\n", array)
array.sort()
print("After sorting\n", array)
# sorting to lower case
print("lower using indexing\n", array[::-1])

Before sorting
 [ 5  9 10  3  1]
After sorting
 [ 1  3  5  9 10]
lower using indexing
 [10  9  5  3  1]


In [55]:
# sorting according to row
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print("Before sorting\n", array)
array.sort(axis=0)
print("After sorting\n", array)

Before sorting
 [[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
After sorting
 [[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


even interval using linspace

In [59]:
# there are 5 datas between 0 to 10
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


난수의 재연

In [83]:
#print(np.random.randint(0, 10, (2, 3)))

np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

[[4 9 6]
 [3 3 7]]


Numpy class copy

In [86]:
array1 = np.arange(0, 10)
array2 = array1
array2[0] = 99
print(array1)

array1 = np.arange(0, 10)
array2 = array1.copy()
array2[0] = 99
print(array1)

[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


Remove duplicate elements 

In [87]:
array = np.array([1, 1, 2, 2, 3, 3, 4])
print(np.unique(array))

[1 2 3 4]
