In [2]:
import numpy as np

array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
# 1 to 3 array
array = np.arange(4)
print(array)

array2 = np.zeros((4, 4), dtype=float)
print(array2)

array3 = np.ones((3, 3,), dtype=str)
print(array3)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [4]:
# 0 to 9 random array

array4 = np.random.randint(0, 10, (3, 3))
print(array4)

# mean is 0, standard deviation is 1 random array

array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[2 2 7]
 [6 0 9]
 [0 7 8]]
[[ 0.03966697  0.34464001  0.28596689]
 [ 0.95249669  1.40421403  0.94280137]
 [-0.83559208  0.06071102 -0.24733698]]


concatenate array

In [5]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [6]:
array1 = np.arange(4).reshape(4, 1)
array2 = np.arange(8).reshape(4, 2)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis=1)
print(array3)

[[0]
 [1]
 [2]
 [3]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 0 1]
 [1 2 3]
 [2 4 5]
 [3 6 7]]


array split

In [9]:
array = np.arange(8).reshape(2, 4)
# vertical split
left, right = np.split(array, [2], axis=1)

print(left)
print(right)

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


numpy ops